FROM node:20-alpine AS build-stage

ENV VITE_API_URL=https://backend-image-w2bv.onrender.com

WORKDIR /app

COPY package*.json ./

RUN npm ci

COPY . .

RUN npm run build

FROM node:20-alpine AS production-stage
WORKDIR /app

COPY --from=build-stage /app/dist ./dist
RUN npm install -g serve

EXPOSE 80
CMD ["sh", "-c", "serve -s dist -l $PORT"]
# CMD ["nginx", "-g", "daemon off;"]